/*
Author: Alexandre Boyer
Date Created: 2018-07-16
*/

/*
This module will simply take the keywords generated by the runners for a given 
document and write them at their appropriate location in the CSV. A mutex will 
be created to ensure data integrity. The IOManager will also allow runners to 
mark a document as complete. That is, when the keywords have been successfully 
written to the CSV, the document is marked as complete and runners won't have 
to work on it again.
*/
